import os
import random

try:
    from google import genai
except ImportError:
    genai = None
    print("⚠️ Gemini client not found — AI summary will use local fallback.")


# 🔹 Try to fetch API key from environment
API_KEY = os.getenv("GEMINI_API_KEY", "").strip()
if not API_KEY and genai:
    print("⚠️ No Gemini API key found. Set GEMINI_API_KEY env variable.")
if genai and API_KEY:
    genai.configure(api_key=API_KEY)


def generate_summary():
    """
    Generates a human-readable AI summary for detected network threats.
    Uses Gemini API if available, else falls back to a local summary generator.
    """
    try:
        # ✅ Use Gemini API (if available and configured)
        if genai and API_KEY:
            client = genai.Client(api_key=API_KEY)
            prompt = (
                "Summarize potential threat patterns observed in network traffic logs. "
                "Describe anomalies in clear technical terms with suggested actions. "
                "Keep it concise, 2-3 sentences."
            )

            response = client.models.generate_content(
                model="gemini-1.5-flash",
                contents=prompt
            )

            summary_text = (
                response.text.strip()
                if hasattr(response, "text")
                else str(response).strip()
            )
            return summary_text or "No summary generated by Gemini."

        # ⚙️ Local fallback
        return random.choice([
            "Network shows stable activity; minimal anomalies detected.",
            "Multiple high-latency connections observed, possibly due to DDoS attempts.",
            "Unusual TCP traffic pattern detected between internal hosts.",
            "Port 22 and 443 show irregular connection spikes. Recommend deeper inspection.",
            "Overall network behavior normal with low anomaly confidence.",
        ])

    except Exception as e:
        print("Gemini API error:", e)
        return "Failed to load AI summary."
